# Generated by Django 3.0.5 on 2020-05-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_auto_20200502_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='statustimein',
            field=models.IntegerField(max_length=11),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='statustimeout',
            field=models.IntegerField(max_length=11),
        ),
    ]
