# Generated by Django 3.0.5 on 2020-05-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_auto_20200502_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='statustimein',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='statustimeout',
            field=models.IntegerField(default=0),
        ),
    ]
