# Generated by Django 3.0.5 on 2020-05-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_auto_20200502_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.IntegerField(choices=[(0, 'InActive'), (1, 'Active')], default=0),
        ),
        migrations.AlterField(
            model_name='leave',
            name='subject',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
