# Generated by Django 3.0.5 on 2020-05-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_auto_20200503_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeenotice',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='managernotice',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(default='EMPLOYEE', max_length=11),
        ),
    ]
